### ISSUE TITLE
nil pointer dereference in authstring

### ISSUE THREAD

**Issue by cuppett** [cuppett/mysql-dba-operator#48]
https://github.com/cuppett/mysql-dba-operator/blob/main/controllers/databaseuser_controller.go#L364-L365

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf7ab34]

goroutine 329 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:118 +0x1a8
panic({0x10deae0, 0x202f310})
	/usr/local/go/src/runtime/panic.go:884 +0x20c
github.com/cuppett/mysql-dba-operator/controllers.(*DatabaseUserReconciler).userDetailString(0x4000802dc0, {0x1520f38?, 0x4000c58ff0?}, 0x40009ffc28, 0x0?)
	/workspace/controllers/databaseuser_controller.go:365 +0xb4
```

**Comment by cuppett** [comment]
I actually think it's here:

https://github.com/cuppett/mysql-dba-operator/blob/v0.0.3/controllers/databaseuser_controller.go#L164
